### ISSUE TITLE
StarRocks 4.0.0 fails to query Iceberg table with "File does not exist" error - points to a stale metadata file

### ISSUE THREAD

**Issue by rotem-ad** [StarRocks/starrocks#65381]
### StarRocks version (Required)

StarRocks 4.0.0-dccb665

### Deployment type

StarRocks cluster on Kubernetes (using [StarRocks Kubernetes Operator](https://github.com/StarRocks/starrocks-kubernetes-operator)) in **shared-data mode**.

### Bug description

After deploying a new cluster with StarRocks v4.0.0-dccb665, it runs properly for a few days. However, at some point, we fail to query one of our production Iceberg tables. It seems StarRocks is trying to access a stale metadata file that no longer exists.

This issue repeats itself every 2-3 days.

### Steps to reproduce (Required)

We are not sure how to reproduce it reliably, as it happens intermittently every 2-3 days on a production table.

### Infrastructure information:

- The Iceberg table is updated and maintained by Apache Spark jobs.

- We use Hive Metastore v3.1.3 as our Iceberg catalog.

- We use HDFS as the storage layer.

### Expected behavior (Required)

Queries on the Iceberg table should execute successfully.

### Real behavior (Required)

Queries fail with "File does not exist" or "Failed to open the off-heap table scanner" errors, pointing to metadata files that are no longer present.

**Example 1: simple `select` query**

`select * from iceberg.schema_name.prod_table limit 5;`

**Error:**

`[42000][1064] File does not exist: hdfs://hdfs-cluster-name/path/to/iceberg/table/metadata/snap-2583631546770153293-1-ea437b69-855a-4fb1-a84a-0581ddfa784d.avro`

**Example 2: Querying snapshots**

`select * from iceberg.schema_name.prod_table$snapshots;`

**Error:**

```
[42000][1064] Failed to open the off-heap table scanner. java exception details: java.io.IOException: Failed to open the IcebergSnapshotsTableScanner
    at com.starrocks.connector.iceberg.AbstractIcebergMetadataScanner.open(AbstractIcebergMetadataScanner.java:76)
Caused by: org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: hdfs://hdfs-cluster-name/path/to/iceberg/table/metadata/22827-34098b81-8440-4746-8919-80291e8bfc7b.metadata.json
```

### Additional important information

- `REFRESH EXTERNAL TABLE` does not work: We tried to run `REFRESH EXTERNAL TABLE iceberg.schema_name.prod_table;` to explicitly update the metadata cached in StarRocks, but the issue persisted.

- **Workaround**: The only workaround that **resolved the issue temporarily** was to manually DROP and CREATE the iceberg external catalog.

- We do not experience this issue in other query engines (e.g., Trino, Apache Spark) querying the same table.

- **Version-specific:** We do not experience this issue in older StarRocks versions. **We successfully queried the exact same table using an existing StarRocks v3.4 cluster with no issues**. This leads us to believe it is a new bug in v4.0.

- **Isolated table:** So far, we've experienced this issue only with one of our production Iceberg tables. The rest of the tables seem to work well, even though they are also maintained by Apache Spark jobs.

**Comment by Wenjun7J** [comment]
Do you know whether Spark runs expire_snapshots or any other maintenance procedures automatically?
I manually executed expire_snapshots in Spark, and everything still worked fine when querying the table from StarRocks.

There are a few things we may need to check:
	1.	Was there any error message in fe.log when refreshing the table?
	2.	Can you provide the sequence of operations performed in Spark and StarRocks to help reproduce the issue?
	3.	Is there anything special about this particular table?

**Comment by mixermt** [comment]
@Wenjun7J 

This is a heavy Iceberg table, up to 2TB data per hour, hourly partitioned, with hundreds of columns, some of them are complex types (if relevant).
Separate Spark jobs performing the writing and table maintenance (retention + expire_snapshots), all actions are done asynchronously, not dependent on one another.
We expire snapshots and DELETE older data on an hourly basis

**Comment by Wenjun7J** [comment]
@mixermt Could you provide the fe logs from the failed query and from the refresh table operation?

**Comment by mixermt** [comment]
@Wenjun7J The only thing we see is 
```
{"@timestamp":"2025-11-16 13:22:40.447Z","level":"ERROR","thread.name":"connector-trigger-analyze-pool-0","thread.id":742,"line":620,"file":"MetadataMgr.java","method":"listPartitionNames","message":"Failed to listPartitionNames on [iceberg_prod.taz_pageviews]","exception":"com.google.common.util.concurrent.UncheckedExecutionException: org.apache.iceberg.exceptions.NotFoundException: File does not exist: hdfs://name-node/schema/table/metadata/snap-7628987438181644072-1-8cb3b1c5-034f-45c7-9c1b-c16c02e268c7.avro\n\tat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085)\n\tat com.google.common.cache.LocalCache.get(LocalCache.java:4011)\n\tat com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4034)\n\tat com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5010)\n\tat com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5017)\n\tat com.starrocks.connector.iceberg.CachingIcebergCatalog.getPartitions(CachingIcebergCatalog.java:288)\n\tat com.starrocks.connector.iceberg.IcebergCatalog.listPartitionNames(IcebergCatalog.java:358)\n\tat com.starrocks.connector.iceberg.CachingIcebergCatalog.listPartitionNames(CachingIcebergCatalog.java:308)\n\tat com.starrocks.connector.iceberg.IcebergMetadata.listPartitionNames(IcebergMetadata.java:542)\n\tat com.starrocks.connector.CatalogConnectorMetadata.listPartitionNames(CatalogConnectorMetadata.java:132)\n\tat com.starrocks.server.MetadataMgr.listPartitionNames(MetadataMgr.java:618)\n\tat com.starrocks.connector.partitiontraits.IcebergPartitionTraits.getPartitionNames(IcebergPartitionTraits.java:82)\n\tat com.starrocks.connector.statistics.ConnectorAnalyzeTask.executeAnalyze(ConnectorAnalyzeTask.java:159)\n\tat com.starrocks.connector.statistics.ConnectorAnalyzeTask.run(ConnectorAnalyzeTask.java:144)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: org.apache.iceberg.exceptions.NotFoundException: File does not exist: hdfs://name-node/schema/table/metadata/snap-7628987438181644072-1-8cb3b1c5-034f-45c7-9c1b-c16c02e268c7.avro\n\tat org.apache.iceberg.hadoop.HadoopInputFile.lazyStat(HadoopInputFile.java:164)\n\tat org.apache.iceberg.hadoop.HadoopInputFile.getLength(HadoopInputFile.java:175)\n\tat com.starrocks.connector.iceberg.io.IcebergCachingFileIO$CachingInputFile.getLength(IcebergCachingFileIO.java:620)\n\tat com.starrocks.connector.iceberg.io.IcebergCachingFileIO$CachingInputFile.newStream(IcebergCachingFileIO.java:630)\n\tat org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:102)\n\tat org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)\n\tat org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37)\n\tat org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:332)\n\tat org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:261)\n\tat org.apache.iceberg.ManifestLists.read(ManifestLists.java:42)\n\tat org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:185)\n\tat org.apache.iceberg.BaseSnapshot.allManifests(BaseSnapshot.java:203)\n\tat org.apache.iceberg.PartitionsTable.planEntries(PartitionsTable.java:198)\n\tat org.apache.iceberg.PartitionsTable.partitions(PartitionsTable.java:175)\n\tat org.apache.iceberg.PartitionsTable.task(PartitionsTable.java:125)\n\tat org.apache.iceberg.PartitionsTable$PartitionsScan.lambda$new$0(PartitionsTable.java:245)\n\tat org.apache.iceberg.StaticTableScan.doPlanFiles(StaticTableScan.java:53)\n\tat org.apache.iceberg.SnapshotScan.planFiles(SnapshotScan.java:139)\n\tat com.starrocks.connector.iceberg.IcebergCatalog.getPartitions(IcebergCatalog.java:310)\n\tat com.starrocks.connector.iceberg.CachingIcebergCatalog.lambda$new$2(CachingIcebergCatalog.java:121)\n\tat com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169)\n\tat com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570)\n\tat com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312)\n\tat com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)\n\tat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)\n\t... 17 more\nCaused by: java.io.FileNotFoundException: File does not exist:  hdfs://name-node/schema/table/metadata/snap-7628987438181644072-1-8cb3b1c5-034f-45c7-9c1b-c16c02e268c7.avro\n\tat org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1832)\n\tat org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1825)\n\tat org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)\n\tat org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1840)\n\tat org.apache.iceberg.hadoop.HadoopInputFile.lazyStat(HadoopInputFile.java:162)\n\t... 41 more\n"}
```

Thank to @yakirgb,
We think the issue is mentioned [here](https://starrocks.slack.com/archives/C02FACZSNJV/p1737157883030129) and [here](https://starrocks.slack.com/archives/C02FACZSNJV/p1735817209258979) and was fixed for HADOOP catalog with the following comment in the end :smiling 

> The current fix only addresses the problem for the Hadoop catalog, but a similar issue might occur with the Glue catalog as well.

Probably hits also HMS based catalog.

**Comment by Wenjun7J** [comment]
@mixermt Thanks, [#54915](https://github.com/StarRocks/starrocks/pull/54915) means the metadata json file names are conflicting. 
That also sounds like a reasonable explanation for this issue.

However, I’m still not sure why the metadata json file names would conflict in your case.
Do you know how those metadata json files were named, or could you share some of the filenames?

Also, could you check the following command?
```
ADMIN SHOW FRONTEND CONFIG LIKE '%iceberg_metadata%';
```
You can try to set `iceberg_metadata_cache_max_entry_size` to 0, and disable `iceberg_metadata_cache_size`. See whether the issue occurs again.

**Comment by mixermt** [comment]
@Wenjun7J  we also don't understand the issue yet, but in the end its working on version 3.4.3/


Output of 
```
ADMIN SHOW FRONTEND CONFIG LIKE '%iceberg_metadata%';

#,Key,Value
1,enable_iceberg_metadata_disk_cache,false
2,iceberg_metadata_cache_disk_path,/opt/starrocks/fe/caches/iceberg
3,iceberg_metadata_cache_max_entry_size,0
4,iceberg_metadata_disk_cache_capacity,2147483648
5,iceberg_metadata_disk_cache_expiration_seconds,604800
6,iceberg_metadata_memory_cache_capacity,0
7,iceberg_metadata_memory_cache_expiration_seconds,86500

```
Yes we will try to disable any cache property and verify if it helps
But this is still a bug :)

**Comment by Wenjun7J** [comment]
@mixermt yes, but the current information is not sufficient to locate the bug, perhaps providing a complete log of when the bug occurred would be helpful

**Comment by rotem-ad** [comment]
@Wenjun7J FYI, seems like completely disabling metadata caching at the Iceberg catalog level fixes the problem (as a workaround):
```
ALTER CATALOG iceberg
SET (
    "enable_iceberg_metadata_cache" = "false"
);
```
BTW, `ALTER CATALOG` command is not documented in StarRock's official documentation, but it actually works :)

**Comment by Wenjun7J** [comment]
@rotem-ad https://github.com/StarRocks/starrocks/issues/65827 We have identified the underlying cause of the problem. I'll try to fix it.
https://github.com/StarRocks/starrocks/pull/56212 this pr adds support for ALTER CATALOG.
I will contact the owner to update the documentation.
Thanks!

**Comment by mixermt** [comment]
@Wenjun7J Great update !
Just to update that in some cases on heavy Iceberg tables we experience up to +20sec overhead for scanning table
